"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os
# driver_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'chromedriver')

APP_NAME = 'KandianTest'

APP = ['home.py']
DATA_FILES = ['Source', 'DBHelper', 'CustomWidget']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'Source/app.icns',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Making Sandwiches",
        'CFBundleIdentifier': "com.metachris.osx.sandwich",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2018, Chris Hager, All Rights Reserved"
    }

}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
